<?php
/**
 * @package     FOF
 * @copyright   2010-2015 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license     GNU GPL version 2 or later
 */

namespace FOF30\Tests\Stubs\Event;

use FOF30\Event\Observable;

class SecondObserver extends FirstObserver
{
	function __construct(Observable &$subject)
	{
		parent::__construct($subject); // TODO: Change the autogenerated stub

		$this->myId = 'two';
	}

	public function onlySecond()
	{
		return 'only second';
	}
}